package forme;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroleriKI.OpstiKontrolerKI;
import modeli.ModelTabeleClanovi;
import modeli.ModelTabelePrimerci;
import niti.OsvezivacFormeVracanje;

public class EkranskaFormaVracanje extends OpstaEkranskaForma {

    private ModelTabeleClanovi modelTabeleClanovi = new ModelTabeleClanovi();
    private ModelTabelePrimerci modelTabelePrimerci = new ModelTabelePrimerci();
    private OsvezivacFormeVracanje ofv;

    public EkranskaFormaVracanje() {
        initComponents();
        postaviImeForme();
        postaviModeleTabela();
        postaviToolTipove();
        pokreniOsvezivac();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtImeClana = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblprezime = new javax.swing.JLabel();
        txtPrezimeClana = new javax.swing.JTextField();
        labelaNapomena = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClanovi = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPrimerci = new javax.swing.JTable();
        btnVrati = new javax.swing.JButton();
        labelaUspesno = new javax.swing.JLabel();
        btnNazadNaGlavnuFormu = new javax.swing.JButton();
        btnNovaPretraga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Odaberite člana koji vraća knjigu:");

        txtImeClana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImeClanaKeyPressed(evt);
            }
        });

        jLabel2.setText("Ime člana:");

        lblprezime.setText("Prezime člana:");

        txtPrezimeClana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrezimeClanaKeyPressed(evt);
            }
        });

        labelaNapomena.setText("Napomena(?)");

        tabelaClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaClanovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClanoviMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClanovi);

        jLabel5.setText("Odaberite primerak knjige koji član vraća:");

        tabelaPrimerci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaPrimerci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPrimerciMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaPrimerci);

        btnVrati.setText("Registruj vraćanje odabranog primerka");
        btnVrati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiActionPerformed(evt);
            }
        });

        labelaUspesno.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(65, 65, 65))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addComponent(txtImeClana, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblprezime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrezimeClana, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelaNapomena, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelaUspesno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnVrati)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelaNapomena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImeClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezimeClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprezime))
                .addGap(5, 5, 5)
                .addComponent(labelaUspesno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVrati)
                .addGap(5, 5, 5))
        );

        btnNazadNaGlavnuFormu.setText("Nazad na glavnu formu");
        btnNazadNaGlavnuFormu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadNaGlavnuFormuActionPerformed(evt);
            }
        });

        btnNovaPretraga.setText("Nova pretraga");
        btnNovaPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPretragaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNazadNaGlavnuFormu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovaPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNazadNaGlavnuFormu)
                    .addComponent(btnNovaPretraga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadNaGlavnuFormuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadNaGlavnuFormuActionPerformed
        nazadNaGlavnuFormu();
    }//GEN-LAST:event_btnNazadNaGlavnuFormuActionPerformed

    private void tabelaClanoviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClanoviMouseClicked
        if (tabelaClanovi.getSelectedRow() != -1) {
            try {
                nadjiIznajmljenePrimerke(modelTabeleClanovi.getLista().get(tabelaClanovi.getSelectedRow()).getSifraClana());
                ofv.setStop(true);
            } catch (Exception ex) {
                Logger.getLogger(EkranskaFormaVracanje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tabelaClanoviMouseClicked

    private void txtImeClanaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeClanaKeyPressed
    }//GEN-LAST:event_txtImeClanaKeyPressed

    private void txtPrezimeClanaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezimeClanaKeyPressed
    }//GEN-LAST:event_txtPrezimeClanaKeyPressed

    private void btnNovaPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPretragaActionPerformed
        ofv = new OsvezivacFormeVracanje();
        ofv.setEfv(this);
        ofv.start();
        modelTabelePrimerci.setLista(new ArrayList<>());
    }//GEN-LAST:event_btnNovaPretragaActionPerformed

    private void btnVratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiActionPerformed
        if (tabelaPrimerci.getSelectedRow() != -1) {
            try {
                vratiPrimerak(modelTabelePrimerci.getLista().get(tabelaPrimerci.getSelectedRow()).getSifraPrimerka());
            } catch (Exception ex) {
                Logger.getLogger(EkranskaFormaVracanje.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Prvo odaberite primerak koji je vraćen.");
        }
    }//GEN-LAST:event_btnVratiActionPerformed

    private void tabelaPrimerciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPrimerciMouseClicked
    }//GEN-LAST:event_tabelaPrimerciMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EkranskaFormaVracanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EkranskaFormaVracanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EkranskaFormaVracanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EkranskaFormaVracanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EkranskaFormaVracanje().setVisible(true);
            }
        });
    }

    @Override
    void postaviImeForme() {
        this.setTitle("Vraćanje primerka knjige");
    }

    @Override
    void postaviModeleTabela() {
        tabelaClanovi.setModel(modelTabeleClanovi);
        tabelaPrimerci.setModel(modelTabelePrimerci);
    }

    @Override
    void postaviToolTipove() {
        labelaNapomena.setToolTipText("Krenite da kucate ime i/ili prezime člana koji želi da vrati knjigu.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazadNaGlavnuFormu;
    private javax.swing.JButton btnNovaPretraga;
    private javax.swing.JButton btnVrati;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelaNapomena;
    private javax.swing.JLabel labelaUspesno;
    private javax.swing.JLabel lblprezime;
    private javax.swing.JTable tabelaClanovi;
    private javax.swing.JTable tabelaPrimerci;
    private javax.swing.JTextField txtImeClana;
    private javax.swing.JTextField txtPrezimeClana;
    // End of variables declaration//GEN-END:variables

    public void osveziTabeluClanova() throws Exception {
        HashMap<String, String> kriterijum = new HashMap<>();
        kriterijum.put("ime", txtImeClana.getText());
        kriterijum.put("prezime", txtPrezimeClana.getText());
        OpstiKontrolerKI.vratiInstancu().osveziTabeluClanova(kriterijum, this);
    }

    private void pokreniOsvezivac() {
        ofv = new OsvezivacFormeVracanje();
        ofv.setEfv(this);
        ofv.start();
    }

    private void nadjiIznajmljenePrimerke(String sifraClana) throws Exception {
        OpstiKontrolerKI.vratiInstancu().nadjiIznajmljenePrimerke(sifraClana, this);
    }

    private void vratiPrimerak(String sifraPrimerka) throws Exception {
        boolean uspesno;
        uspesno = OpstiKontrolerKI.vratiInstancu().vratiPrimerak(sifraPrimerka);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Sistem je evidentirao vraćanje primerka");
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da evidentira vraćanje primerka");
        }
    }

    //setteri i getteri
    
    
    
    public ModelTabeleClanovi getModelTabeleClanovi() {
        return modelTabeleClanovi;
    }

    public void setModelTabeleClanovi(ModelTabeleClanovi modelTabeleClanovi) {
        this.modelTabeleClanovi = modelTabeleClanovi;
    }

    public ModelTabelePrimerci getModelTabelePrimerci() {
        return modelTabelePrimerci;
    }

    public void setModelTabelePrimerci(ModelTabelePrimerci modelTabelePrimerci) {
        this.modelTabelePrimerci = modelTabelePrimerci;
    }

    public javax.swing.JTable getTabelaClanovi() {
        return tabelaClanovi;
    }

    public void setTabelaClanovi(javax.swing.JTable tabelaClanovi) {
        this.tabelaClanovi = tabelaClanovi;
    }

    public javax.swing.JTable getTabelaPrimerci() {
        return tabelaPrimerci;
    }

    public void setTabelaPrimerci(javax.swing.JTable tabelaPrimerci) {
        this.tabelaPrimerci = tabelaPrimerci;
    }

    //neimplementirane
    @Override
    void popuniTabele() {
        throw new UnsupportedOperationException("Metoda koju ste pozvali nije još implementirana.");
    }
    
    @Override
    HashMap<String, String> kreirajObjekat() {
        throw new UnsupportedOperationException("Metoda koju ste pozvali nije još implementirana."); //To change body of generated methods, choose Tools | Templates.
    }

    public javax.swing.JLabel getLabelaUspesno() {
        return labelaUspesno;
    }

    public void setLabelaUspesno(javax.swing.JLabel labelaUspesno) {
        this.labelaUspesno = labelaUspesno;
    }
}
